/*1. Დაბეჭდეთ რიცხვები 2 დან 8 მდე

let a=2;

while (a<9){
    
    console.log(a)
    
    a++
    if (a>7) break 
} */

    /*2. 5 დან 35 - ის ჩათვლით დაბეჭდეთ ყოველი მეოთხე რიცხვი (უნდა დაიბეჭდოს 5,9,13…))

let number
for(number=5; number<=35; number+=4)
{
    console.log(number)
} */

    /*3. დაბეჭდეთ 3 დან 8 მდე რიცხვების ნამრავლი
let sum=1
for(i=3; i<8; i++){
    sum=sum*i
} console.log(sum)*/


    /*4. Გამოაცხადეთ ობიექტი person რომელსაც აქვს firstName, lastName, age და დაბეჭდეთ person-სრული სახელი ( სახელი და გვარი)
     let person={
        firstname: "Ana",
        lastname: "Garcia",
        age: 55,
    
     }
     console.log(person.firstname, person.lastname) */

     /*5. დაბეჭდეთ მეოთხე დავალებაში გამოცხადებული პერსონის თითოეული property value 
let person={
    firstname: "Ana",
    lastname: "Garcia",
    age: 55,

 }
 for (const key in person){
    console.log(key, person[key])
 }  */

    /*6. დაწერეთ მასივი fruits ელემენტებით ["Apple", "Banana", "Orange"]; დაბეჭდეთ მასივის თითოეული წევრი.

let fruit = ["Apple", "Banana", "Orange"]
console.log(fruit) */


/*. დაამატეთ fruits მასივის თავში Grapes და ბოლოში  Pineapples დაბეჭდეთ fruits

let fruit = ["Apple", "Banana", "Orange"]

fruit.push("pineapples")
fruit.unshift("grapes")
console.log(fruit) */

/*8.დაბეჭდეთ 1 დან 34 მდე რიცხვების ჯამი
let sum=0
for(i=1; i<34; i++){
    sum=sum+i
}
console.log(sum) */








    





